services:
  mc:
    container_name: ${NAME}
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      ENABLE_ROLLING_LOGS: "true"
      TYPE: NEOFORGE
      GENERICK_PACK: downloads/${MODPACK_NAME}.zip
    env_file:
      - ${ENV_FILE}
    ports:
      - "${PORT}:25565"
    volumes:
      - ${DATADIR}:/data
      - ./plugins:/plugins
      - ./config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        compress: "true"
        mode: "non-blocking"
        tag: "{{.Name}}"
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536