services:
  mc:
    container_name: ${NAME:-minecraft_server}
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      ENABLE_ROLLING_LOGS: "true"
      # Add modpack configuration
      MODPACK_PLATFORM: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-8"
      CF_API_KEY: ${CF_API_KEY}
      # Increase memory for modpack
      MEMORY: "8G"
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "${PORT:-25565}:25565"
    volumes:
      - ${DATADIR:-data}:/data
      - ./plugins:/plugins
      - ./config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        compress: "true"
        mode: "non-blocking"
        tag: "{{.Name}}"
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${CPUS:-3}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536